name: totem
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

assets:
  - assets/

environment:
  sdk: ^3.10.7

dependencies:
  drift: ^2.30.1
  drift_flutter: ^0.2.8
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  path_provider: ^2.1.5
  shared_preferences: ^2.5.4

dev_dependencies:
  build_runner: ^2.10.5
  drift_dev: ^2.30.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
