name: totem
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

assets:
  - assets/
fonts:
  - family: Nunito
    fonts:
      - asset: assets/fonts/nunito-extralight.ttf
        weight: 200
      - asset: assets/fonts/nunito-extralightitalic.ttf
        weight: 200
        style: italic
      - asset: assets/fonts/nunito-light.ttf
        weight: 300
      - asset: assets/fonts/nunito-lightitalic.ttf
        weight: 300
        style: italic
      - asset: assets/fonts/nunito-regular.ttf
        weight: 400
      - asset: assets/fonts/nunito-italic.ttf
        weight: 400
        style: italic
      - asset: assets/fonts/nunito-medium.ttf
        weight: 500
      - asset: assets/fonts/nunito-mediumitalic.ttf
        weight: 500
        style: italic
      - asset: assets/fonts/nunito-semibold.ttf
        weight: 600
      - asset: assets/fonts/nunito-semibolditalic.ttf
        weight: 600
        style: italic
      - asset: assets/fonts/nunito-bold.ttf
        weight: 700
      - asset: assets/fonts/nunito-bolditalic.ttf
        weight: 700
        style: italic
      - asset: assets/fonts/nunito-extrabold.ttf
        weight: 800
      - asset: assets/fonts/nunito-extrabolditalic.ttf
        weight: 800
        style: italic
      - asset: assets/fonts/nunito-black.ttf
        weight: 900
      - asset: assets/fonts/nunito-blackitalic.ttf
        weight: 900
        style: italic

environment:
  sdk: ^3.10.7

dependencies:
  animate_do: ^4.2.0
  calendar_view: ^1.4.0
  connectivity_plus: ^7.0.0
  dio: ^5.9.0
  drift: ^2.30.1
  drift_flutter: ^0.2.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.4
  geolocator: ^14.0.2
  get_it: ^9.2.0
  go_router: ^17.0.1
  logger: ^2.6.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.4
  toastification: ^3.0.3
  window_manager: ^0.5.1

dev_dependencies:
  build_runner: ^2.10.5
  change_app_package_name: ^1.5.0
  drift_dev: ^2.30.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
